
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Dec 08 11:55:10 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 8;
  public static final int ELSE = 12;
  public static final int PLUS = 15;
  public static final int THEN = 11;
  public static final int SEMI = 21;
  public static final int CHAR = 5;
  public static final int LEFTPAR = 17;
  public static final int END = 7;
  public static final int RIGHTPAR = 18;
  public static final int IF = 10;
  public static final int COLON = 19;
  public static final int WRITE = 9;
  public static final int ID = 13;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 6;
  public static final int COMMA = 22;
  public static final int EOF = 0;
  public static final int DOT = 23;
  public static final int CONST = 14;
  public static final int error = 1;
  public static final int ASSIGN = 20;
  public static final int INTEGER = 4;
  public static final int MUL = 16;
  public static final int VAR = 3;
}

