
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Dec 16 11:50:59 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 7;
  public static final int RIGHTBRACKET = 6;
  public static final int PLUS = 18;
  public static final int INT = 11;
  public static final int CHAR = 12;
  public static final int LEFTPAR = 3;
  public static final int RIGHTPAR = 4;
  public static final int COLON = 17;
  public static final int ID = 9;
  public static final int COMMA = 10;
  public static final int FLOAT = 13;
  public static final int EOF = 0;
  public static final int WHEN = 15;
  public static final int MAIN = 2;
  public static final int MINUS = 19;
  public static final int LEFTBRACKET = 5;
  public static final int CONST = 16;
  public static final int CASE = 8;
  public static final int error = 1;
  public static final int ASSIGN = 14;
}

