
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 09 01:00:34 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 2;
  public static final int error = 1;
  public static final int PLUS = 3;
  public static final int PUTA = 4;
  public static final int EOF = 0;
}

